version: "3"
services:
  nvidia:
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    container_name: proto
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "7860:7860"
      - "8000:8000"
    command: ["top"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]